name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS 


on:
    workflow_dispatch:
        inputs:
            base-branch:
                type: string
                description: The brancch used as the base for the dependency update Checks
                default: main
            target-branch:
                type: string
                description: The branch from which the PR is created
                default: update-dependencies
            working-directory:
                description: The working directory of the project to check for dependency update
            gh-token:
                description: Authentication token with repository access. Must have write accessto contents and pull-requests
            debug:
                description: Whether the output debug messages to the console
                type: boolean
                default: false

jobs:
    dependency-update: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check fo dependency updates
              uses: ./.github/actions/js-dependency-update
          