name: 17 - 3 - Custom Actions - Docker
#run-name: 17 - 3 - Custom Actions - Docker  ||  URL - ${{ inputs.url }} 


on:
    workflow_dispatch:
        inputs:
            url:
                type: string
                default: 'https://www.google.com'
<<<<<<< HEAD
            max_trials:
                type: string
            delay:
                type: string
=======
   
>>>>>>> 68a8747 (fix(17-3-custom-actions): fixing and uploading dockerfile)


jobs:
    docker-ping: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{ inputs.url }}
<<<<<<< HEAD
                #max_trials: ${{ inputs.max_trials }}
                #delay: ${{ inputs.delay }}


          

=======
          
>>>>>>> 68a8747 (fix(17-3-custom-actions): fixing and uploading dockerfile)

